# -*- coding: utf-8 -*-
"""library.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nMBdpkQ6T0N9P8m9ZdNtzLz2_jTKf2WR
"""

#Login module
from datetime import datetime #Importing timestamp into the program
login_details ={'librarian':{'passkey': 'manage@95', 'role': 'librarian'},'Emma001': {'passkey':'dat001','role':'user'}, 'Gee002':{'passkey':'dat002','role':'user'},'Nancy': {'passkey':'dat003','role': 'user'}}
def validate_user(user_id, passkey): #creating a function that can sign users into the system
    if user_id in login_details and login_details[user_id]['passkey']==passkey:
        print(f'Welcome to the digital library, {user_id}')
        return login_details[user_id]['role']

    else:
        print('Access denied')
        return None



#book management module
def creating_book(title, author, isbn, year): #creating a function that permits the librarian to create books
  return {"ISBN": isbn, "title": title, "author": author, "genre": input("Enter genre"), "year":year,  "status": "available", "renter": None, "rent_count": 0, "Rent_time": None, "Return_time": None}
library=[{"ISBN": 1001, "title": "To kill a Mockingbird", "author": "Harper Lee", "genre": "fiction", "year": 1960, "status":"available","renter":None, "Rent_time": None,"Return_time": None, "rent_count":0},{"ISBN": 1002,"title":"1984","author": "George Orwell", "genre": "Dystopian","year": 1949,"status":"available","renter":None, "Rent_time": None,"Return_time": None, "Rent_count":0}]
def adding_book(library,book):#creating a function that permits the librarian to add books
    library.append(book)
    print(f"Book '{book['title']}' added successfully")

def deleting_book(library,title): #creating a function that permits the librarian to delete books
    for book in library:
        if book["title"]==title:
           library.remove(book)
           print(f"You have deleted '{title}'")
           return
    print(f"The book '{title}' does not exist in library")

def viewing_book(library, search_term=None, search_by="title"): #creating a function that permits the users to view and search for books
    if not isinstance(library, list) or not library:
        print("No book found")
        return

    search_fields = {"title", "author", "genre", "year"}
    if search_by not in search_fields:
        print("Search field not valid")
        return

    print("Books in the library:")
    found_books = False

    for book in library:
        match = False
        if search_term:
            if search_by == "title" and search_term.lower() in book.get("title", "").lower():
                match = True
            elif search_by == "author" and search_term.lower() in book.get("author", "").lower():
                match = True
            elif search_by == "genre" and search_term.lower() in book.get("genre", "").lower():
                match = True
            elif search_by == "year" and str(search_term) == str(book.get("year", "")):
                match = True
        else:
            match = True

        if match:
            print_book_details(book)
            found_books = True

    if not found_books:
        print("No match found")

def print_book_details(book):
    print(f"Title: {book.get('title', 'N/A')}, Author: {book.get('author', 'N/A')}, "
          f"Genre: {book.get('genre', 'N/A')}, Year: {book.get('year', 'N/A')}")



def renting_book(library,title, user_id): #creating a function that permits the user to rent books
    for book in library:
        if book["title"] == title:
           if book["status"] == "available":
              book["status"] = "rented"
              book["renter"] = user_id
              #book["rent_count"] +=1
              book["rent_count"] = book.get("rent_count",0)+1
              book["Rent_time"] = datetime.now().strftime("%d-%m-%Y %H:%M:%S")
              print(f" '{book['title']}' rented")
              return
           else:
              print(f"'{book['title']}' unavailable for rent")
              return
    print(f"The book, '{title}' not in the library")


def returning_book(library,title): #creating a function that permits the user to return books
    for book in library:
        if book["title"] == title:
           if book["status"] == "rented":
              book["renter"] = None
              book["Return_time"] = datetime.now().strftime("%d-%m-%Y %H:%M:%S")
              book["status"] = "available"
              print(f" '{book['title']}' returned")
              return
           else:
              print(f" '{book['title']}' not rented")
              return
    print(f"'{title}' not in the library")

def viewing_rentedbooks(library):#creating a function that permits users to view rented books
    books_rented = [book for book in library if book["status"] == "rented"]
    if not books_rented:
       print("There are no rented books")
    else:
        print("Books rented:")
        for book in books_rented:
            print(f"Title: {book['title']},Author: {book['author']},Genre: {book['genre']}, Year: {book['year']}, Renter:{book['renter']}, Rent time: {book.get('Rent_time')},Return Time:{book.get('Return_time')}")

#Book analytics
def count_total_books(library):
    return len(library)

def count_rented_books(library):
    return len([book for book in library if book["status"] == "rented"])

def count_available_books(library):
    return len([book for book in library if book["status"] == "available"])

#Menu module
def menu(library, user_role):
    while True:
        print("1. Add book")
        print("2. Delete book")
        print("3. View all books")
        print("4. Rent book")
        print("5. Return book")
        print("6. View rented book")
        print("7. Analytics")
        print("8. Search books")
        print("9. Exit")


        user_choice = input("Select an option:")
        if user_choice == "1":
          if user_role == "librarian":
           title = input("Enter title of book:")
           author = input("Enter author of book:")
           isbn = input("Enter ISBN:")
           year=input("Enter year the book was published:")
           adding_book(library, creating_book(title,author,isbn,year))
          else:
              print("You do not have access to this function. Please select a valid input")
        elif user_choice == "2":
          if user_role == 'librarian':
               title = input("Enter title of book:")
               deleting_book(library, title)
          else:
              print("You do not have access to this function. Please select a valid input")
        elif user_choice == "3":
         viewing_book(library)
        elif user_choice == "4":
         title=input("Enter book title:")
         user_id=input("Enter your user_id:")
         renting_book(library,title, user_id)
        elif user_choice == "5":
         title = input ("Enter book title:")
         returning_book(library,title)
        elif user_choice == "6":
            viewing_rentedbooks(library)
        elif user_choice == "7":
         print(f"Total books: {count_total_books(library)}")
         print(f"Rented books: {count_rented_books(library)}")
         print(f"Available books:{count_available_books(library)}")
        elif user_choice == "8":
          search_term = input("Enter search term:")
          search_by = input("Search by (title, author, genre, year):")
          viewing_book(library, search_term, search_by)
        elif user_choice == "9":
         print("Exiting library")
         break
    else:
        print("Invalid input. Please select a valid option.")

#default library containing preloaded books

def main ():
  library =[{"ISBN": 1001, "title": "To kill a Mockingbird", "author": "Harper Lee", "genre": "fiction", "year": 1960, "status":"available","renter":None, "Rent_time": None,"Return_time": None, "rent_count":0},{"ISBN": 1002,"title":"1984","author": "George Orwell", "genre": "Dystopian","year": 1949,"status":"available","renter":None, "Rent_time": None,"Return_time": None,"rent_count":0}]
  user_id = input("Enter user_id:")
  passkey = input ("Enter password:")
  user_role = validate_user(user_id,passkey)
  if user_role:
       menu(library,user_role)
  else:
        print("Exiting library")

if __name__ == "__main__":
  main()

